Update eslint to version 5.5.0
archived-codacy/codacy-eslint-legacy pull request #103
Opened 2018-09-14 20:55 UTC by FloEdelmann

And add all rules that were added to eslint since version 4.15.0

2018-09-16 09:10 UTC, rtfpessoa requested changes

2018-09-16 09:10 UTC, rtfpessoa commented on src/main/resources/docs/tests/no-invalid-regexp.js
> -//#Err: no-invalid-regexp
This should still report an error according to eslint website https://eslint.org/docs/rules/no-invalid-regexp

2018-09-16 11:01 UTC, FloEdelmann commented on src/main/resources/docs/tests/no-invalid-regexp.js
> -//#Err: no-invalid-regexp
True, it actually should throw an error, but it doesn't. I opened an issue in the eslint repository: https://github.com/eslint/eslint/issues/10861

2018-10-03 21:56 UTC, sstern6 commented on src/main/resources/docs/tests/no-invalid-regexp.js
> -//#Err: no-invalid-regexp
Is it possible to merge this PR in and then when that fix is in we can make another PR for the minor version update.  Because technically this is the way eslint 5.6.0 works right now.  When this is fixed itll be a diff version.  Unless this PR is meant to cover all eslint rules from 5.6.0 - 5.7.0? 

Also, FYI I will be fixing this week https://github.com/eslint/eslint/issues/10861

@rtfpessoa 

Thank you

2018-10-04 18:28 UTC, rtfpessoa commented on src/main/resources/docs/tests/no-invalid-regexp.js
> -//#Err: no-invalid-regexp
@sstern6 I would prefer to wait a bit more to avoid a regression in the product. It can lead to weird cases.

2018-10-04 19:59 UTC, sstern6 commented on src/main/resources/docs/tests/no-invalid-regexp.js
> -//#Err: no-invalid-regexp
ok I understand, so then when that fix is merged in codacy will support eslint 5.6.x with the updated fix and will dependent on Eslint next release?  How will subsequent releases but handled with eslint.  Will a new PR be created in this repo for every minor or major version?

Thanks

2018-10-09 15:53 UTC, rtfpessoa commented on src/main/resources/docs/tests/no-invalid-regexp.js
> -//#Err: no-invalid-regexp
Ideally every release we do a new PR here to update the version.

2018-10-09 17:13 UTC, sstern6 commented on src/main/resources/docs/tests/no-invalid-regexp.js
> -//#Err: no-invalid-regexp
Ok sounds good @rtfpessoa.  PR for this issue has been merged in https://github.com/eslint/eslint/pull/10920.  Im guessing this will make it into the 5.6.2 release, so we will either need to update this PR to support 5.6.2 and label it asa such.  Or merge this in and make another PR for 5.6.2.

Given our previous conversation I assume you would like to update this PR?

2018-10-09 21:39 UTC, rtfpessoa commented
I just would not like to merge this one since it disables a test. I would
prefer to fix it first.

On Tue, 9 Oct 2018, 6:13 pm Scott Stern, <notifications@github.com> wrote:

> *@sstern6* commented on this pull request.
> ------------------------------
>
> In src/main/resources/docs/tests/no-invalid-regexp.js
> <https://github.com/codacy/codacy-eslint/pull/103#discussion_r223788237>:
>
> > @@ -4,7 +4,6 @@
>  RegExp('[');
>  //#Err: no-invalid-regexp
>  RegExp('.', 'z');
> -//#Err: no-invalid-regexp
>
> Ok sounds good @rtfpessoa <https://github.com/rtfpessoa>. PR for this
> issue has been merged in eslint/eslint#10920
> <https://github.com/eslint/eslint/pull/10920>. Im guessing this will make
> it into the 5.6.2 release, so we will either need to update this PR to
> support 5.6.2 and label it asa such. Or merge this in and make another PR
> for 5.6.2.
>
> Given our previous conversation I assume you would like to update this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/codacy/codacy-eslint/pull/103#discussion_r223788237>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA3E8HnycJPeF_2mRxgdrZfjKj2936LOks5ujNkjgaJpZM4Wp7-6>
> .
>

2018-10-12 19:50 UTC, sstern6 commented
@rtfpessoa eslint 5.7.0 has been released with the fix that you requested.  @FloEdelmann would you mind updating this PR and name to support 5.7.0?  https://eslint.org/blog/2018/10/eslint-v5.7.0-released

Does that sound ok to everyone?

2018-10-12 20:32 UTC, FloEdelmann commented
@sstern6 Done. Thanks for your updates on this!

2018-10-13 13:39 UTC, rtfpessoa commented
@FloEdelmann should I continue the update or will you take care of it?

2018-10-14 03:51 UTC, rtfpessoa approved these changes

2018-10-14 12:12 UTC, merged