Feature/add new plugins
archived-codacy/codacy-eslint-legacy pull request #135
Opened 2019-06-04 23:29 UTC by peavers

Adds requested plugins and preforms minor package maintenance.

2019-06-06 10:03 UTC, bmbferreira approved these changes

2019-06-06 10:23 UTC, bmbferreira requested changes
All the new plugins should be added to the config file that we will use when none is provided. This file is generated on the ESLint.scala file

2019-06-06 10:23 UTC, bmbferreira commented on build.sbt
> +     |npm install -g eslint-plugin-compat@3.1.1 &&
don't forget to add this to ESLint.scala

2019-06-06 10:23 UTC, bmbferreira commented on build.sbt
> +     |npm install -g eslint-config-kentcdodds@14.3.2 &&
don't forget to add this to ESLint.scala

2019-06-06 20:55 UTC, peavers commented on build.sbt
> +     |npm install -g eslint-config-kentcdodds@14.3.2 &&
This one being only a config rather than a plugin doesn't need to be added if I understood the code correctly?

2019-06-07 07:57 UTC, bmbferreira approved these changes

2019-06-07 07:57 UTC, bmbferreira commented on build.sbt
> +     |npm install -g eslint-config-kentcdodds@14.3.2 &&
ops! you're right. this comment was only valid for compat plugin!

2019-06-07 08:38 UTC, DReigada approved these changes

2019-06-07 18:25 UTC, merged